# Configuration file for hosting documents on readthedocs.io
# See, https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/conf.py
